/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoordenacaoRouteImport } from './routes/coordenacao'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as IndexRouteImport } from './routes/index'

const CoordenacaoRoute = CoordenacaoRouteImport.update({
  id: '/coordenacao',
  path: '/coordenacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/coordenacao': typeof CoordenacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/coordenacao': typeof CoordenacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/coordenacao': typeof CoordenacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aluno' | '/coordenacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aluno' | '/coordenacao'
  id: '__root__' | '/' | '/aluno' | '/coordenacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRoute
  CoordenacaoRoute: typeof CoordenacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/coordenacao': {
      id: '/coordenacao'
      path: '/coordenacao'
      fullPath: '/coordenacao'
      preLoaderRoute: typeof CoordenacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRoute,
  CoordenacaoRoute: CoordenacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
